server:
  port: 8200

spring:
  application:
    name: upload-server

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 60
    height: 60
  tracker-list:
    - 81.70.229.244:22122

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

baidu:
  upload:
    path:
      windows: D:\\images
      linux: /yxl/images
    img:
      host: http://81.70.229.244/